apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: simple-page-health
  namespace: simple-page

spec:
  metrics:

    - name: success-rate

      interval: 30s

      count: 3

      failureLimit: 1

      successCondition: result[0] >= 0.95

      provider:

        prometheus:

          address: http://prometheus-operated.monitoring.svc:9090

          query: |
            sum(
              rate(
                http_requests_total{
                  namespace="simple-page",
                  status=~"2.."
                }[1m]
              )
            )
            /
            sum(
              rate(
                http_requests_total{
                  namespace="simple-page"
                }[1m]
              )
            )
