apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: simple-page
  namespace: simple-page
spec:
  replicas: 4

  revisionHistoryLimit: 3

  selector:
    matchLabels:
      app: simple-page

  template:
    metadata:
      labels:
        app: simple-page
    spec:
      containers:
        - name: simple-page
          image: rono23/simple-page:latest

          ports:
            - containerPort: 80

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10

  strategy:
    canary:
      canaryService: simple-page-canary
      stableService: simple-page

      steps:
        - setWeight: 10
        - pause:
            duration: 30s

        - analysis:
            templates:
              - templateName: simple-page-health

        - setWeight: 25
        - pause:
            duration: 30s

        - analysis:
            templates:
              - templateName: simple-page-health

        - setWeight: 50
        - pause:
            duration: 30s

        - analysis:
            templates:
              - templateName: simple-page-health

        - setWeight: 100
