apiVersion: argoproj.io/v1alpha1
kind: Rollout

metadata:
  name: simple-page
  namespace: simple-page

spec:
  replicas: 4

  revisionHistoryLimit: 3

  selector:
    matchLabels:
      app: simple-page

  template:
    metadata:
      labels:
        app: simple-page

    spec:
      containers:
        - name: simple-page

          image: rono23/simple-page:39

          ports:
            - containerPort: 80

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10

  strategy:
    canary:
      stableService: simple-page
      canaryService: simple-page-canary

      steps:

        # 10% traffic
        - setWeight: 10

        - pause:
            duration: 30s

        # 25% traffic
        - setWeight: 25

        - pause:
            duration: 30s

        # 50% traffic
        - setWeight: 50

        - pause:
            duration: 30s

        # 100% traffic
        - setWeight: 100
